RMS-HIPAA/RMS-HIPAA/Controllers/SelfRiskAssessmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using RMS_HIPAA.Models.SelfRiskAssessmentModel;

namespace RMS_HIPAA.Controllers
{
    public class SelfRiskAssessmentController : Controller
    {
        // GET: SelfRiskAssessment
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AdministrativeSelfRiskAssessmentQuestions()
        {
            return View();
        }

        public ActionResult PhysicalSelfRiskAssessmentQuestions()
        {
            return View();
        }

        public ActionResult TechnologySelfRiskAssessmentQuestions()
        {
            return View();
        }

        public async Task<PartialViewResult> _editSelfRiskAssessmentQuestion(int id)
        {
            var model = new SelfRiskAssessmentQuestionsViewModel();
            return PartialView(model);
        }

        public async Task<PartialViewResult> _addSelfRiskAssessmentQuestion(string FunctionName)
        {
            var model = new SelfRiskAssessmentQuestionsViewModel();
            model.RiskType = FunctionName;
            return PartialView(model);
        }
    }
}

RMS-HIPAA/RMS-HIPAA/Views/SelfRiskAssessment/AdministrativeSelfRiskAssessmentQuestions.cshtml
@{
    ViewBag.Title = "Self Risk Assessment Questions List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="main-content-inner">
    <div class="row">
        <div class="col-xs-12">
            <h3 class="header smaller lighter blue"> </h3>
            <div class="table-header">
                Self Risk Assessment Questions List
            </div>
            <div>
                <button class="btn btn-sm btn-primary" type="submit" id="AddQuestionsButton" onclick="javascript: addSelfRiskAssessmentQuestion_Window('Administrative');">
                    Add Questions
                </button>
            </div>
            <table id="TableList" class="table table-striped table-bordered table-hover">
                <thead style="background-color:red;">
                    <tr>
                        <td style="font-weight:lighter; color:white; background-color:#6faed9;" hidden>ID</td>                       
                        <td style="font-weight:lighter; color:white; background-color:#6faed9;" hidden>RiskType</td>
                        <td style="font-weight:lighter; color:white; background-color:#6faed9;">Serial #</td>
                        <td style="font-weight:lighter; color:white; background-color:#6faed9;">Questions</td>
                        <td style="font-weight:lighter;color:white; background-color:#6faed9;">Actions</td>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>

        </div>
    </div>
</div>
<div id="addSelfRiskquestion"></div>
<div id="editSelfRiskquestion"></div>

@section Scripts{

    @*@Scripts.Render("~/bundles/SelfRiskAssessment")*@
    <script type="text/javascript" src="~/Scripts/Areas/SelfRiskAssessment/SelfRiskAssessment.js"></script>
    <script type="text/javascript">
        window.AddSelfAssessmentQuestionsUrl = "@Url.Action("_addSelfRiskAssessmentQuestion", "SelfRiskAssessment")";
            $(document).ready(function () {
                DisplayLeaveRequests("Administrative");
            });
    </script>
}










RMS-HIPAA/RMS-HIPAA/Views/SelfRiskAssessment/PhysicalSelfRiskAssessmentQuestions.cshtml
@{
    ViewBag.Title = "Self Risk Assessment Questions List";
    Layout = "~/Views/Shared/_LayoutPhysical.cshtml";
}

<div class="main-content-inner">
    <div class="row">
        <div class="col-xs-12">
            <h3 class="header smaller lighter blue"> </h3>
            <div class="table-header">
                Self Risk Assessment Questions List
            </div>
            <div>
                <button class="btn btn-sm btn-primary" type="submit" id="AddQuestionsButton" onclick="javascript: addSelfRiskAssessmentQuestion_Window('Physical');">
                    Add Questions
                </button>
            </div>
            <table id="TableList" class="table table-striped table-bordered table-hover">
                <thead style="background-color:red;">
                    <tr>
                        <td style="font-weight:lighter; color:white; background-color:#6faed9;" hidden>ID</td>
                        <td style="font-weight:lighter; color:white; background-color:#6faed9;" hidden>RiskType</td>
                        <td style="font-weight:lighter; color:white; background-color:#6faed9;">Serial #</td>
                        <td style="font-weight:lighter; color:white; background-color:#6faed9;">Questions</td>
                        <td style="font-weight:lighter;color:white; background-color:#6faed9;">Actions</td>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>

        </div>
    </div>
</div>
<div id="addSelfRiskquestion"></div>
<div id="editSelfRiskquestion"></div>

@section Scripts{

    @*@Scripts.Render("~/bundles/SelfRiskAssessment")*@
    <script type="text/javascript" src="~/Scripts/Areas/SelfRiskAssessment/SelfRiskAssessment.js"></script>
    <script type="text/javascript">
        window.AddSelfAssessmentQuestionsUrl = "@Url.Action("_addSelfRiskAssessmentQuestion", "SelfRiskAssessment")";
            $(document).ready(function () {
                DisplayLeaveRequests("Physical");
            });
    </script>
}










RMS-HIPAA/RMS-HIPAA/Views/SelfRiskAssessment/TechnologySelfRiskAssessmentQuestions.cshtml
@{
    ViewBag.Title = "Self Risk Assessment Questions List";
    Layout = "~/Views/Shared/_LayoutTechnology.cshtml";
}

<div class="main-content-inner">
    <div class="row">
        <div class="col-xs-12">
            <h3 class="header smaller lighter blue"> </h3>
            <div class="table-header">
                Self Risk Assessment Questions List
            </div>
            <div>
                <button class="btn btn-sm btn-primary" type="submit" id="AddQuestionsButton" onclick="javascript: addSelfRiskAssessmentQuestion_Window('Technology');">
                    Add Questions
                </button>
            </div>
            <table id="TableList" class="table table-striped table-bordered table-hover">
                <thead style="background-color:red;">
                    <tr>
                        <td style="font-weight:lighter; color:white; background-color:#6faed9;" hidden>ID</td>
                        <td style="font-weight:lighter; color:white; background-color:#6faed9;" hidden>RiskType</td>
                        <td style="font-weight:lighter; color:white; background-color:#6faed9;">Serial #</td>
                        <td style="font-weight:lighter; color:white; background-color:#6faed9;">Questions</td>
                        <td style="font-weight:lighter;color:white; background-color:#6faed9;">Actions</td>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>

        </div>
    </div>
</div>
<div id="addSelfRiskquestion"></div>
<div id="editSelfRiskquestion"></div>

@section Scripts{

    @*@Scripts.Render("~/bundles/SelfRiskAssessment")*@
    <script type="text/javascript" src="~/Scripts/Areas/SelfRiskAssessment/SelfRiskAssessment.js"></script>
    <script type="text/javascript">
        window.AddSelfAssessmentQuestionsUrl = "@Url.Action("_addSelfRiskAssessmentQuestion", "SelfRiskAssessment")";
            $(document).ready(function () {
                DisplayLeaveRequests("Technology");
            });
    </script>
}










RMS-HIPAA/RMS-HIPAA/Views/SelfRiskAssessment/_addSelfRiskAssessmentQuestion.cshtml
@model RMS_HIPAA.Models.SelfRiskAssessmentModel.SelfRiskAssessmentQuestionsViewModel

<div class="row">
    <div class="col-sm-12">
        @using (Html.BeginForm("AddSelfRiskAssessmentQuestion", "SelfRiskAssessment", null, FormMethod.Post, new { role = "form", @class = "form-horizontal", @id = "SRiskQuestionForm", @name = "SRiskQuestionForm" }))
        {
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">

                        <i class="ace-icon fa fa-angle-down bigger-110" data-icon-hide="ace-icon fa fa-angle-down" data-icon-show="ace-icon fa fa-angle-right"></i>
                        &nbsp;Self Assessment Questions

                    </h4>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-xs-12">
                            @Html.HiddenFor(model => model.RiskType)
                            <div class="row">
                                <div class="form-group">
                                    <div class="col-sm-12">
                                        <div class="col-md-12">
                                            @Html.LabelFor(m => m.Questions);
                                            @Html.TextBoxFor(m => m.Questions, "", new { @id = "Questions", @name = "Questions", @class = "form-control risk-field" })
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
                <div class="clearfix form-actions risk-panel" style="color:white">
                    <div class="col-md-6">
                        <button id="saveSRiskQuestionBtn" class="btn btn-info btn-mini" type="button">
                            <i class="ace-icon fa fa-check"></i>
                            Save
                        </button>

                    </div>
                </div>
            </div>
        }
    </div>
</div>

<script type="text/javascript">

    if("@Request.QueryString["risktype"]" != 'undefined')
    {
        $("#RiskType").val(@Request.QueryString["risktype"]);
    }



    $('#saveSRiskQuestionBtn').click(function (e) {
        var isValid = true;
        if($.trim($('#Questions').val()) == '')
        {
            isValid = false;
            $('#Questions').addClass('errorClass');
        }
        else
        {
            $('#Questions').removeClass('errorClass');
        }

        if(isValid)
        {
            var formData = $('#SRiskQuestionForm').serialize();
            var CurrentDialog = $("#addSelfRiskquestion");
            $.ajax({
                type: "post",
                data: formData,
                url: "../api/SelfRiskAssessmentDetails",
                dataType: "json",       //    if you want to return json data, enable this data type.
                success: function (data) {
                    var FunctionName = $("#RiskType").val();
                    CurrentDialog.dialog("close");
                    CurrentDialog.empty();
                    //alert(FunctionName);
                    DisplayLeaveRequests(FunctionName);
                    HIPAA.Alert("Self RiskAssessment Questions added successfully", "success");
                },
                error: function (request, status, error) {
                    HIPAA.Alert("Failed to add the Self RiskAssessment Questions", "danger");
                }
            });
        }
        else
        {
            e.preventDefault();
            return false;
        }
    });
</script>

RMS-HIPAA/RMS-HIPAA/Views/SelfRiskAssessment/_editSelfRiskAssessmentQuestion.cshtml
@model RMS_HIPAA.Models.SelfRiskAssessmentModel.SelfRiskAssessmentQuestionsViewModel

<div class="row">
    <div class="col-sm-12">
        @using (Html.BeginForm("EditSelfRiskAssessmentQuestion", "SelfRiskAssessment", null, FormMethod.Post, new { role = "form", @class = "form-horizontal", @id = "SRiskQuestionForm", @name = "SRiskQuestionForm" }))
        {
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">

                        <i class="ace-icon fa fa-angle-down bigger-110" data-icon-hide="ace-icon fa fa-angle-down" data-icon-show="ace-icon fa fa-angle-right"></i>
                        &nbsp;Self Assessment Questions

                    </h4>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-xs-12">
                            @Html.HiddenFor(model => model.Id)
                            @Html.HiddenFor(model => model.RiskType)
                            <div class="row">
                                <div class="form-group">
                                    <div class="col-sm-12">
                                        <div class="col-md-12">
                                            @Html.LabelFor(m => m.Questions)
                                            @Html.TextBoxFor(m => m.Questions, "", new { @id = "Questions", @name = "Questions", @class = "form-control risk-field" })
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
                <div class="clearfix form-actions risk-panel" style="color:white">
                    <div class="col-md-6">
                        <button id="saveSRiskQuestionBtn" class="btn btn-info btn-mini" type="button">
                            <i class="ace-icon fa fa-check"></i>
                            Save
                        </button>

                    </div>
                </div>
            </div>
        }
    </div>
</div>

<link href="~/Content/css/RMS/RiskAssessment.css" rel="stylesheet" />
<script type="text/javascript">
    if("@Request.QueryString["id"]" != 'undefined')
    {
        ShowDetails("@Request.QueryString["id"]");
    }
    else
    {
        HIPAA.Alert("Failed to load the Self RiskAssessment Questions", "danger");
        //$("#savePRiskAssessBtn").attr('disabled', 'disabled');
    }

    function ShowDetails(id) {

        var myurl = '../api/SelfRiskAssessmentDetails/' + id
        $.ajax(
        {
            url: myurl,
            type: 'GET',
            dataType: 'json',
            success: function (data) {
               // alert(data.questions);
                $("#Id").val(data.id);
                $("#RiskType").val(data.riskType);
                $("#Questions").val(data.questions);
            },
            error: function (xhr, status, error) {
                HIPAA.Alert("Failed to load the Self RiskAssessment Questions", "danger");
            }
        });
    }

    $('#saveSRiskQuestionBtn').click(function (e) {
        var isValid = true;
        if($.trim($('#Questions').val()) == '')
        {
            isValid = false;
            $('#Questions').addClass('errorClass');
        }
        else
        {
            $('#Questions').removeClass('errorClass');
        }

        if(isValid)
        {
            var formData = $('#SRiskQuestionForm').serialize();
            var CurrentDialog = $("#editSelfRiskquestion");
            $.ajax({
                type: "put",
                data: formData,
                url: "../api/SelfRiskAssessmentDetails",
                dataType: "json",       //    if you want to return json data, enable this data type.
                success: function (data) {
                    var FunctionName = $("#RiskType").val();
                    CurrentDialog.dialog("close");
                    DisplayLeaveRequests(FunctionName);
                    HIPAA.Alert("Self RiskAssessment Questions updated successfully", "success");
                },
                error: function (request, status, error) {
                    HIPAA.Alert("Failed to save the Self RiskAssessment Questions", "danger");
                }
            });
        }
        else
        {
            e.preventDefault();
            return false;
        }
    });

</script>