RMS-HIPAA/RMS-HIPAA/Models/AssetInventoryModel/HardwareInventoryViewModel.cs
using RMS_HIPAA.DAL;
using RMS_HIPAA.Framework.Service;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;


namespace RMS_HIPAA.Models.AssetInventoryModel
{
    public class HardwareInventoryViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Asset Id")]
        public string AssetId { get; set; }

        [Display(Name = "Asset Class")]
        public string AssetClass { get; set; }
        public SelectList AssetClassList { get; private set; }

        [Display(Name = "Host/System Name")]
        public string SystemName { get; set; }

        [Display(Name = "Description")]
        public string Description { get; set; }

        [Display(Name = "Make/Model")]
        public string Model { get; set; }
       

        [Display(Name = "Type")]
        public string Type { get; set; }

        [Display(Name = "Hardware Criticality")]
        public string HardwareCriticality { get; set; }
        public SelectList HardwareCriticalityList { get; private set; }

        [Display(Name = "Risk assess frequency")]
        public string RiskAssessFreq { get; set; }
        public SelectList RiskAssessFreqList { get; private set; }

        [Display(Name = "Business Function")]
        public string BusinessFunction { get; set; }
        public SelectList BusinessFunctionList { get; private set; }

        [Display(Name = "System/Business Owner")]
        public string BusinessOwnerName { get; set; }

        [Display(Name = "Department/Function")]
        public string Department { get; set; }
        public SelectList DepartmentList { get; private set; }

        public DateTime? CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public HardwareInventoryViewModel() { }

        public async Task InitializeValues()
        {
            AssetId = RiskAssessmentService.GenerateAssetID();
            await PopulateListData(null,  null, null, null, null);
        }
        private async Task PopulateListData(string AssetClassVal,string HardwareCriticalityVal,  string AssessFreqVal, string FunctionVal, string DeptVal)
        {
            try
            {
                using (var db = new RMSHIPAAEntities())
                {
                    var responsibleDepts = await db.Departments.ToListAsync();
                    DepartmentList = new SelectList(responsibleDepts, "Name", "Name", DeptVal);

                    var assetClasses = new List<KeyValuePair<string, string>>
                    {
                        //Laptop, Mobile/Handheld devices,Network Infrastructure, Server Hadware,
                        new KeyValuePair<string, string>("Laptop", "Laptop"),
                        new KeyValuePair<string, string>("Mobile/Handheld devices", "Mobile/Handheld devices"),
                        new KeyValuePair<string, string>("Network Infrastructure", "Network Infrastructure"),
                        new KeyValuePair<string, string>("Server Hadware", "Server Hadware"),
                    };
                    AssetClassList = new SelectList(assetClasses, "Key", "Value", AssetClassVal);

                    

                    var hardwareCriticality = new List<KeyValuePair<string, string>>
                    {
                        new KeyValuePair<string, string>("High", "High"),
                        new KeyValuePair<string, string>("Medium", "Medium"),
                        new KeyValuePair<string, string>("Low", "Low"),
                    };
                    HardwareCriticalityList = new SelectList(hardwareCriticality, "Key", "Value", HardwareCriticalityVal);

                    

                    var riskAssessFreq = new List<KeyValuePair<string, string>>
                    {
                        //As per policy, Ahdoc/Need basis.

                        new KeyValuePair<string, string>("As per policy", "As per policy"),
                        new KeyValuePair<string, string>("Ahdoc/Need basis", "Ahdoc/Need basis"),
                    };
                    RiskAssessFreqList = new SelectList(riskAssessFreq, "Key", "Value", AssessFreqVal);

                    var business = new List<KeyValuePair<string, string>>
                    {
                        //Patient Treatment, Patient billing, Healthcare Operations, Communications

                        new KeyValuePair<string, string>("Patient Treatment", "Patient Treatment"),
                        new KeyValuePair<string, string>("Patient billing", "Patient billing"),
                        new KeyValuePair<string, string>("Healthcare OperationsOption 3", "Healthcare Operations"),
                        new KeyValuePair<string, string>("Communications", "Communications"),
                    };
                    BusinessFunctionList = new SelectList(business, "Key", "Value", FunctionVal);
                }

            }
            catch (Exception ex)
            {
                RMS_HIPAA.Framework.Log.Logger.LogError(ex);
            }
        }

        public DAL.HardwareInventory ConvertToHardwareInventory()
        {
            var SI = new DAL.HardwareInventory
            {
                AssetId = AssetId,
                AssetClass = AssetClass,
                SystemName = SystemName,
                Description = Description,
                Model = Model,
               // Type = Type,
                HardwareCriticality = HardwareCriticality,                
                RiskAssessFrequencey = RiskAssessFreq,
                BusinessFunction = BusinessFunction,
                BusinessOwner = BusinessOwnerName,
                Department = Department,
                CreatedBy = "Indidge",
                CreatedOn = DateTime.UtcNow
            };
            return SI;
        }

        public HardwareInventoryViewModel ConvertFromSoftwareInventory(DAL.HardwareInventory SI)
        {
            Id = SI.Id;
            AssetId = SI.AssetId;
            AssetClass = SI.AssetClass;
            SystemName = SI.SystemName;
            Description = SI.Description;
            Model = SI.Model;
            Type=SI.Type;
            HardwareCriticality = SI.HardwareCriticality;
            RiskAssessFreq = SI.RiskAssessFrequencey;
            BusinessFunction = SI.BusinessFunction;
            BusinessOwnerName = SI.BusinessOwner;
            Department = SI.Department;
            CreatedBy = SI.CreatedBy;
            CreatedOn = SI.CreatedOn;
            ModifiedBy = SI.ModifiedBy;
            ModifiedOn = SI.ModifiedOn;

            return this;
        }

        public HardwareInventoryViewModel(DAL.HardwareInventory SI)
        {
            Id = SI.Id;
            AssetId = SI.AssetId;
            AssetClass = SI.AssetClass;
            SystemName = SI.SystemName;
            Description = SI.Description;
            Model = SI.Model;
            Type=SI.Type;
            HardwareCriticality = SI.HardwareCriticality;
            RiskAssessFreq = SI.RiskAssessFrequencey;
            BusinessFunction = SI.BusinessFunction;
            BusinessOwnerName = SI.BusinessOwner;
            Department = SI.Department;
            CreatedBy = SI.CreatedBy;
            CreatedOn = SI.CreatedOn;
            ModifiedBy = SI.ModifiedBy;
            ModifiedOn = SI.ModifiedOn;
        }
    }
}

RMS-HIPAA/RMS-HIPAA/Controllers/InventoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using RMS_HIPAA.Models.AssetInventoryModel;

namespace RMS_HIPAA.Controllers
{
    public class InventoryController : Controller
    {
        // GET: Inventory
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SoftwareInventoryView()
        {
            return View();
        }

        public ActionResult HardwareInventoryView()
        {
            return View();
        }

        public async Task<PartialViewResult> _addSWItem()
        {
            var model = new SoftwareInventoryViewModel();
            await model.InitializeValues();
            return PartialView(model);
        }
        public async Task<PartialViewResult> _editSWItem(int id)
        {
            var model = new SoftwareInventoryViewModel();
            await model.InitializeValues();
            return PartialView(model);
        }

        public async Task<PartialViewResult> _addHWItem()
        {
            var model = new HardwareInventoryViewModel();
            await model.InitializeValues();
            return PartialView(model);
        }
        public async Task<PartialViewResult> _editHWItem(int id)
        {
            var model = new HardwareInventoryViewModel();
            await model.InitializeValues();
            return PartialView(model);
        }
    }
}

RMS-HIPAA/RMS-HIPAA/Views/Inventory/HardwareInventoryView.cshtml

@{
    ViewBag.Title = "HardwareInventoryView";
    Layout = "~/Views/Shared/_LayoutTechnology.cshtml";
}

@Scripts.Render("~/bundles/jqueryJS")
@Scripts.Render("~/bundles/jqueryPackage")

<div class="main-content-inner">
    <div class="breadcrumbs ace-save-state" id="breadcrumbs">
        <ul class="breadcrumb">
            <li>
                <i class="ace-icon fa fa-folder-open-o"></i>
                <a href="#">Asset Inventory</a>
            </li>

            <li>
                <i class="ace-icon fa fa-file-text"></i>
                <a href="#">Hardware Asset</a>
            </li>

        </ul>
    </div>
    <div class="row">
        <div class="col-xs-12">

           
            <table id="HardwareInventoryTable" class="table table-striped table-bordered table-hover" style="width:100%">
                <thead style="background-color:red;">
                    <tr>
                        <td style="font-weight:lighter; color:white; background-color:#6faed9;">ID</td>
                        <td style="font-weight:lighter; color:white; background-color:#6faed9;">Asset Id</td>
                        <td style="font-weight:lighter; color:white; background-color:#6faed9;">Asset Class</td>
                        <td style="font-weight:lighter; color:white; background-color:#6faed9;">Host Name</td>
                        <td style="font-weight:lighter; color:white; background-color:#6faed9;">Description</td>                       
                        <td style="font-weight:lighter; color:white; background-color:#6faed9;">Make/Model</td>
                        <td style="font-weight:lighter; color:white; background-color:#6faed9;">Type</td>
                        <td style="font-weight:lighter; color:white; background-color:#6faed9;">Hardware Criticality</td>                        
                        <td style="font-weight:lighter; color:white; background-color:#6faed9;">Risk assess frequencey</td>
                        <td style="font-weight:lighter; color:white; background-color:#6faed9;">Business Function</td>
                        <td style="font-weight:lighter; color:white; background-color:#6faed9;">Business Owner</td>
                        <td style="font-weight:lighter; color:white; background-color:#6faed9;">Department</td>
                        <td style="font-weight:lighter;color:white; background-color:#6faed9;">Actions</td>
                    </tr>
                </thead>

            </table>

        </div>
    </div>
</div>
<div id="addHWInventoryItem"></div>
<div id="editHWInventoryItem"></div>
 @section Scripts{

        @Scripts.Render("~/bundles/RiskAssessment")
<!--<script type="text/javascript" src="~/Scripts/Areas/RiskAssessment/RiskAssessment.js"></script>-->
<script type="text/javascript">
    $(document).ready(function () {

                DisplayHardwareInventory();
            });
</script>
    }


RMS-HIPAA/RMS-HIPAA/Views/Inventory/_addHWItem.cshtml
@model RMS_HIPAA.Models.AssetInventoryModel.HardwareInventoryViewModel

<div class="row">
    <div class="col-sm-12">
        @using (Html.BeginForm("addHWItemform", "Inventory", null, FormMethod.Post, new { role = "form", @class = "form-horizontal", @id = "addHWItemForm", @name = "addHWItemForm" }))
        {
        <div id="accordion" class="accordion-style1 panel-group">
            <div class="panel panel-default risk-panel">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a class="accordion-toggle risk-panel" style="color:white;" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                            <i class="ace-icon fa fa-angle-down bigger-110" data-icon-hide="ace-icon fa fa-angle-down" data-icon-show="ace-icon fa fa-angle-right"></i>
                            &nbsp;Hardware Inventory Details
                        </a>
                    </h4>
                </div>
                <div class="panel-collapse collapse in" id="collapseOne">
                    <div class="panel-body">

                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="col-md-3">
                                        @Html.LabelFor(m => m.AssetId)
                                        @Html.TextBoxFor(m => m.AssetId, "", new { @class = "form-control risk-field", @readonly = "readonly" })
                                    </div>
                                    <div class="col-md-3">
                                        @Html.LabelFor(m => m.AssetClass)
                                        @Html.DropDownListFor(m => m.AssetClass, Model.AssetClassList, "Select a Asset Class...", new { @class = "form-control chosen-select" })
                                    </div>
                                    <div class="col-md-3">
                                        @Html.LabelFor(m => m.SystemName);
                                        @Html.TextBoxFor(m => m.SystemName, "", new { @class = "form-control risk-field"})
                                    </div>
                                    <div class="col-md-3">
                                        @Html.LabelFor(m => m.Model);
                                        @Html.TextBoxFor(m => m.Model, "", new { @class = "form-control risk-field"})
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="col-md-9">
                                        @Html.LabelFor(m => m.Description)
                                        <br />
                                        @Html.TextAreaFor(m => m.Description, new { @class = "form-control risk-field" })
                                    </div>
                                    
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="col-md-4">
                                        @Html.LabelFor(m => m.HardwareCriticality)
                                        @Html.DropDownListFor(m => m.HardwareCriticality, Model.HardwareCriticalityList, "Select an option...", new { @class = "form-control chosen-select" })
                                    </div>
                                    <div class="col-md-4">
                                        @Html.LabelFor(m => m.Type);
                                        @Html.TextBoxFor(m => m.Type, "", new { @class = "form-control risk-field"})
                                    </div>
                                    <div class="col-md-4">
                                        @Html.LabelFor(m => m.RiskAssessFreq)
                                        @Html.DropDownListFor(m => m.RiskAssessFreq, Model.RiskAssessFreqList, "Select an option...", new { @class = "form-control chosen-select" })
                                    </div>
                                </div>
                            </div>
                            <div class="space"></div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="col-md-4">
                                        @Html.LabelFor(m => m.BusinessFunction)
                                        @Html.DropDownListFor(m => m.BusinessFunction, Model.BusinessFunctionList, "Select an option...", new { @class = "form-control chosen-select" })
                                    </div>
                                    <div class="col-md-4">
                                        @Html.LabelFor(m => m.BusinessOwnerName)
                                        @Html.TextBoxFor(m => m.BusinessOwnerName, "", new { @class = "form-control risk-field"})
                                    </div>
                                    <div class="col-md-4">
                                        @Html.LabelFor(m => m.Department)
                                        @Html.DropDownListFor(m => m.Department, Model.DepartmentList, "Select an option...", new { @class = "form-control chosen-select" })
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="clearfix form-actions risk-panel" style="color:white">
                            <div class="col-md-offset-10 ">
                                <button id="saveHWItemBtn" class="btn btn-info btn-mini" type="button">
                                    <i class="ace-icon fa fa-check"></i>
                                    Save
                                </button>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        }
    </div>
</div>

<link href="~/Content/css/RMS/RiskAssessment.css" rel="stylesheet" />

    @Scripts.Render("~/bundles/RiskAssessment")
<script type="text/javascript">
        $(document).ready(function () {
            $("#saveHWItemBtn").click(function (e) {
                var formData = $('#addHWItemForm').serialize();
                $.ajax({
                    type: "POST",
                    data: formData,
                    url: "../api/HardwareInventoryDetails",
                    dataType: "json",       //    if you want to return json data, enable this data type.
                    success: function (data) {
                        $("#addHWInventoryItem").dialog("close");
                        $("#addHWInventoryItem").empty();
                        HIPAA.Alert("Hardware asset inventory details saved successfully", "success");
                        DisplayHardwareInventory();
                    },
                    error: function (request, status, error) {
                        $("#addHWInventoryItem").dialog("close");
                        HIPAA.Alert("Failed to save the Hardware asset inventory details", "danger");
                    }
                });
            });
        });
</script>



RMS-HIPAA/RMS-HIPAA/Views/Inventory/_addSWItem.cshtml
@model RMS_HIPAA.Models.AssetInventoryModel.SoftwareInventoryViewModel

<div class="row">
    <div class="col-sm-12">
        @using (Html.BeginForm("addSWItemform", "Inventory", null, FormMethod.Post, new { role = "form", @class = "form-horizontal", @id = "addSWItemForm", @name = "addSWItemForm" }))
        {
        <div id="accordion" class="accordion-style1 panel-group">
            <div class="panel panel-default risk-panel">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a class="accordion-toggle risk-panel" style="color:white;" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                            <i class="ace-icon fa fa-angle-down bigger-110" data-icon-hide="ace-icon fa fa-angle-down" data-icon-show="ace-icon fa fa-angle-right"></i>
                            &nbsp;Software Inventory Details
                        </a>
                    </h4>
                </div>
                <div class="panel-collapse collapse in" id="collapseOne">
                    <div class="panel-body">
                        
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="col-md-3">
                                            @Html.LabelFor(m => m.AssetId)
                                            @Html.TextBoxFor(m => m.AssetId, "", new { @class = "form-control risk-field", @readonly = "readonly" })
                                        </div>
                                        <div class="col-md-3">
                                            @Html.LabelFor(m => m.AssetClass)
                                            @Html.DropDownListFor(m => m.AssetClass, Model.AssetClassList, "Select a Asset Class...", new { @class = "form-control chosen-select" })
                                        </div>
                                        <div class="col-md-3">                                            
                                            @Html.LabelFor(m => m.ApplicationName);
                                            @Html.TextBoxFor(m => m.ApplicationName, "", new { @class = "form-control risk-field"})        
                                        </div>
                                        <div class="col-md-3">
                                            @Html.LabelFor(m => m.Os)
                                            @Html.DropDownListFor(m => m.Os, Model.OSList, "Select a Asset Class...", new { @class = "form-control chosen-select" })
                                        </div>
                                     </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="col-md-9">
                                            @Html.LabelFor(m => m.Description)
                                            <br />
                                            @Html.TextAreaFor(m => m.Description, new { @class = "form-control risk-field" })
                                        </div>
                                        <div class="col-md-3">
                                            <br/>
                                            @Html.LabelFor(m => m.Shared)
                                            &nbsp;&nbsp; 
                                            @Html.RadioButtonFor(model => model.Shared, "Yes", new { name = "Shared", @checked = true }) Yes
                                            &nbsp;&nbsp;
                                            @Html.RadioButtonFor(model => model.Shared, "No", new { name = "Shared" }) No
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="col-md-4">
                                            @Html.LabelFor(m => m.ApplicationCriticality)
                                            @Html.DropDownListFor(m => m.ApplicationCriticality, Model.ApplicationCriticalityList, "Select an option...", new { @class = "form-control chosen-select" })
                                        </div>
                                        <div class="col-md-4">
                                            @Html.LabelFor(m => m.DataClassification)
                                            @Html.DropDownListFor(m => m.DataClassification, Model.DataClassificationList, "Select an option...", new { @class = "form-control chosen-select" })
                                        </div>
                                        <div class="col-md-4">
                                            @Html.LabelFor(m => m.RiskAssessFreq)
                                            @Html.DropDownListFor(m => m.RiskAssessFreq, Model.RiskAssessFreqList, "Select an option...", new { @class = "form-control chosen-select" })
                                        </div>
                                    </div>
                                </div>
                                <div class="space"></div>
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="col-md-4">
                                            @Html.LabelFor(m => m.BusinessFunction)
                                            @Html.DropDownListFor(m => m.BusinessFunction, Model.BusinessFunctionList, "Select an option...", new { @class = "form-control chosen-select" })
                                        </div>
                                        <div class="col-md-4">
                                            @Html.LabelFor(m => m.BusinessOwnerName)
                                            @Html.TextBoxFor(m => m.BusinessOwnerName, "", new { @class = "form-control risk-field"})        
                                        </div>
                                        <div class="col-md-4">
                                            @Html.LabelFor(m => m.Department)
                                            @Html.DropDownListFor(m => m.Department, Model.DepartmentList, "Select an option...", new { @class = "form-control chosen-select" })
                                        </div>
                                    </div>
                                </div>                      
                            </div>                            
                        <div class="clearfix form-actions risk-panel" style="color:white">
                            <div class="col-md-offset-10 ">
                                <button id="saveSWItemBtn" class="btn btn-info btn-mini" type="button">
                                    <i class="ace-icon fa fa-check"></i>
                                    Save
                                </button>
                            </div>
                        </div>                     
                    </div>
                    
                </div>
            </div>
        </div>
        }
    </div>
</div>

<link href="~/Content/css/RMS/RiskAssessment.css" rel="stylesheet" />

    @Scripts.Render("~/bundles/RiskAssessment")
    <script type="text/javascript">
        $(document).ready(function () {
            $("#saveSWItemBtn").click(function (e) {
                var formData = $('#addSWItemForm').serialize();
                $.ajax({
                    type: "POST",
                    data: formData,
                    url: "../api/SoftwareInventoryDetails",
                    dataType: "json",       //    if you want to return json data, enable this data type.
                    success: function (data) {
                        $("#addSWInventoryItem").dialog("close");
                        $("#addSWInventoryItem").empty();
                        HIPAA.Alert("Software asset inventory details saved successfully", "success");
                        DisplaySoftwareInventory();
                    },
                    error: function (request, status, error) {
                        $("#addSWInventoryItem").dialog("close");
                        HIPAA.Alert("Failed to save the Software asset inventory details", "danger");
                    }
                });
            });
        });
    </script>
        